### ISSUE TITLE
image id error

### ISSUE THREAD

**Issue by mavsan** [morawskim/faker-images#2]
If you specify the desired image `picID` - url is formed with an error, [here](https://github.com/morawskim/faker-images/blob/master/src/PicsumProvider.php#L14) you need to add a slash (sorry for my english):

```
if ($id) {
    $url = 'id/' . $id . '/';
}
```

Without this slash, the url looks like this : https://picsum.photos/id/10041110/400, and should be like this: https://picsum.photos/id/1004/1110/400

**Comment by morawskim** [comment]
Fixed
