### ISSUE TITLE
Advanced Usage

### ISSUE THREAD

**Issue by emtiazzahid** [morawskim/faker-images#3]
This is an awesome package. I have a suggestion. 
There is a section called advanced usage in [picsum website](https://picsum.photos/). for example, my need was to get the exact image [URL](https://picsum.photos/200/300.jpg) with the jpg extension. I think it will be good for others. Thanks
![image](https://user-images.githubusercontent.com/10188029/104984026-2af06c80-5a38-11eb-9d2c-e8c40ac86278.png)

**Comment by morawskim** [comment]
Thanks for the suggestion. I added an additional parameter to set an image extension.
